"""Deterministic synthetic data: canonical rows for demo mode and benchmarks (PLAN §5).

Raw export files for streaming and parser benchmarks are generated by each connector's own
`synth_<id>.py`, implementing `sherd_connectors.synth.raw.RawGenerator`.
"""

from sherd_connectors.synth.generator import (
    PROFILES,
    SELF_IDENTITIES,
    TZ,
    Profile,
    fingerprint,
    generate,
    source_of,
)
from sherd_connectors.synth.importer import CONNECTOR_ID, VERSION, import_profile

__all__ = [
    "CONNECTOR_ID",
    "PROFILES",
    "SELF_IDENTITIES",
    "TZ",
    "VERSION",
    "Profile",
    "fingerprint",
    "generate",
    "import_profile",
    "source_of",
]
